# Generated by Django 3.2.7 on 2021-09-21 18:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('full_name', models.CharField(max_length=254)),
                ('university', models.CharField(blank=True, max_length=254, null=True)),
                ('nip', models.IntegerField(blank=True, null=True)),
                ('field_of_study', models.CharField(max_length=254)),
                ('position', models.CharField(choices=[('Asisten Ahli', 'Asisten_Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor_Kepala'), ('Guru Besar/Professor', 'Guru_Besar_Professor')], max_length=254)),
                ('role', models.CharField(choices=[('Dosen', 'Dosen'), ('Reviewer', 'Reviewer'), ('SDM PT', 'SDM_PT'), ('Admin', 'Admin')], max_length=254)),
                ('approved', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KaryaIlmiah',
            fields=[
                ('karil_id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.TextField(max_length=254)),
                ('journal_data', models.TextField()),
                ('link_origin', models.TextField(blank=True, null=True)),
                ('link_repo', models.TextField(blank=True, null=True)),
                ('link_indexer', models.TextField(blank=True, null=True)),
                ('link_simcheck', models.TextField(blank=True, null=True)),
                ('link_correspondence', models.TextField(blank=True, null=True)),
                ('indexer', models.TextField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('Not Reviewed Yet', 'Not_Reviewed_Yet'), ('In Review', 'In_Review'), ('Done', 'Done'), ('Not Assigned Yet', 'Not_Assigned_Yet'), ('Requested', 'Requested'), ('Done', 'Done')], max_length=254)),
                ('promotion', models.CharField(choices=[('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Profesor', 'Profesor')], max_length=254)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('plagiarism_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('linearity', models.CharField(max_length=254)),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
                ('comment_1', models.CharField(blank=True, max_length=254)),
                ('comment_2', models.CharField(blank=True, max_length=254)),
                ('comment_3', models.CharField(blank=True, max_length=254)),
                ('comment_4', models.CharField(blank=True, max_length=254)),
                ('score_proposer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('karil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.karyailmiah')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
