# Generated by Django 3.2.7 on 2021-10-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='journal_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karyailmiah',
            name='promotion',
            field=models.CharField(choices=[('Asisten Ahli', 'Asisten_Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor_Kepala'), ('Guru Besar/Professor', 'Guru_Besar_Professor')], max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='nip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
