# Generated by Django 3.2.7 on 2021-10-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211002_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
