# Generated by Django 3.2.7 on 2021-11-06 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211010_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyailmiah',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='karyailmiah',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='main.Review'),
        ),
    ]
